name: Backend CI/CD Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: "dc+o#2fmc+352(l1h*yo2rfv!a(e^n)bcy17$&zdreamutt+*p"
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_ENGINE: "postgresql"
      POSTGRES_DB: "edemy"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
        working-directory: ./server
      - name: Run linting (Flake8)
        run: |
          pip install flake8
          flake8 .
        working-directory: ./server
      - name: Unit tests
        run: pytest
        working-directory: ./server

  e2e:
    runs-on: ubuntu-latest
    needs: [react, django]
    env:
      VITE_APP_TITLE: "Edemy ðŸŽ“ - Discover and learn about any topic ðŸ”–"
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./client/web

      - name: Build React app
        run: npm run build
        working-directory: ./client/web

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./client/web

      - name: Run Playwright E2E Tests
        run: npm run e2e:ci
        working-directory: ./client/web

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./client/web/playwright-report
          retention-days: 30